name: fineartsociety
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  carousel_slider: 4.2.1
  url_launcher: ^6.0.13
  http:
  shared_preferences: ^2.2.2
  loading_animation_widget: ^1.2.0+4
  timer_count_down: ^2.2.2
  flutter_svg: ^2.0.9
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  flutter_icon_snackbar: ^1.1.4
  flutter_rating_bar: ^4.0.1
  getwidget: ^4.0.0
  page_view_dot_indicator: ^2.3.0
  another_transformer_page_view: ^2.0.1
  google_maps_flutter: ^2.2.8
  simple_ripple_animation: ^0.0.9
  hovering: ^1.0.4
  video_player: ^2.8.2
  flutter_polyline_points: ^2.0.0
  location: ^5.0.0-dev.8
  animated_emoji: ^3.1.0
  razorpay_web: ^1.4.2
  flutter_dotenv: ^5.1.0
  flutter_stripe: ^10.1.0
  flutter_stripe_web: ^5.1.0
  font_awesome_flutter: ^10.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  riverpod_generator: ^2.3.9
  build_runner: ^2.4.7
  custom_lint: ^0.5.7
  riverpod_lint: ^2.3.7

flutter:
  uses-material-design: true

  assets:
  
    - assets/
    - lib/
    - assets/altrd-vid.mp4

    # Add paths to all artist images
  fonts:
    - family: Cinzel
      fonts:
        - asset: assets/fonts/Cinzel.ttf
    - family: Brown
      fonts:
        - asset: assets/fonts/Brown.otf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Black.ttf
          weight: 900
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 500
